### PR TITLE
Add past talks dir and put 2022-03-01 Python FP talk in it

### PR DESCRIPTION
**Pull request by tadhg-ohiggins**
Pure, immutable:
The only way to be sure.
Who needs side effects?

-----

Material for my [Functional programming in Python](https://github.com/18F/tech-talks/issues/63) talk.

Also, I added a directory for past talks and suggest we put talk material in subdirectories of that with the name format `YYYY-MM-DD--title`.

### CODE REVIEW

**Comment by geekygirlsarah** [comment]
We have a google drive for past videos and slides and such. I'd be fine with stuff here for sharing purposes, but also feel like videos and slides being together might be better too. I'm torn.

**Comment by tadhg-ohiggins** [comment]
@geekygirlsarah yeah, it's tricky; we definitely don't want videos in the repo, but on the other hand Google Drive is poor for discoverability. I think I'd vote for keeping non-video materials in both places (even though that's repetitive!) and maybe having a file in the repo directory with a URL for the equivalent Google Drive folder. I'm not certain about this, though.

**Comment by tadhg-ohiggins** [comment]
Also I uploaded my talk to the relevant Google Drive folder, thanks for the reminder.

**Comment by geekygirlsarah** [comment]
Looks like I can't undo this merge easily.  Can you rename the folder to "talk-materials" or "talk-slides" so it's a bit more specific? "past-talks" isn't really specific to what's in there. (I'll do the same on the Google drive to try to clarify it)

**Comment by tadhg-ohiggins** [comment]
@geekygirlsarah https://github.com/18F/tech-talks/pull/69

**Pull request merged**
